import json
from typing import AsyncGenerator, Optional, Dict, Any
import openai
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logger import logger
from app.ai.memory_manager import MemoryManager
from app.ai.tools_definition import AI_TOOLS
from app.ai.tool_executor import ToolExecutor
from app.ai.response_sanitizer import sanitize_ai_response
from app.services.rag_service import RAGService

class GPT4ConversationEngine:
    """
    Core AI Engine with streaming audio response and function calling execution.
    Prioritizes real-time dynamic business data and uploaded documents,
    enforcing zero technical jargon and accurate intent-based responses.
    """

    def __init__(self, memory_manager: MemoryManager, db: AsyncSession, organization_id: Any):
        self.memory = memory_manager
        self.db = db
        self.organization_id = organization_id
        self.client = openai.AsyncOpenAI(api_key=settings.OPENAI_API_KEY)
        self.model = settings.OPENAI_MODEL
        self.executor = ToolExecutor(db, organization_id)
        self.rag_service = RAGService(db, organization_id)

    async def generate_response_stream(self, user_transcript: str) -> AsyncGenerator[str, None]:
        """
        Processes caller transcript, analyzes intent independently,
        executes dynamic business data search or document retrieval,
        and yields natural assistant response chunks.
        """
        user_text = user_transcript.strip()
        self.memory.add_user_message(user_text)

        # Fallback / Development mode: Dynamic dual-source retrieval & reasoning
        if not settings.OPENAI_API_KEY or settings.OPENAI_API_KEY == "sk-proj-mock-key-for-development":
            dual_result = await self.rag_service.query_dual_source(
                user_text,
                session_id=str(self.organization_id),
                conversation_history=self.memory.get_messages()
            )
            response_text = sanitize_ai_response(dual_result["answer"])

            self.memory.add_assistant_message(response_text)
            yield response_text
            return

        try:
            # 1. First completion call with dynamic tools enabled
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=self.memory.get_messages(),
                tools=AI_TOOLS,
                tool_choice="auto",
                temperature=0.6,
                stream=False
            )

            message = response.choices[0].message

            # 2. Handle Tool Calls if generated by GPT-4
            if message.tool_calls:
                self.memory.add_raw_message(message.model_dump())

                for tool_call in message.tool_calls:
                    fn_name = tool_call.function.name
                    fn_args = tool_call.function.arguments
                    tool_result = await self.executor.execute_tool(fn_name, fn_args)
                    self.memory.add_tool_message(tool_call.id, tool_result)

                # Stream final synthesized response after tool execution
                stream = await self.client.chat.completions.create(
                    model=self.model,
                    messages=self.memory.get_messages(),
                    temperature=0.6,
                    stream=True
                )

                full_text = ""
                async for chunk in stream:
                    content = chunk.choices[0].delta.content or ""
                    if content:
                        clean_chunk = sanitize_ai_response(content)
                        full_text += clean_chunk
                        yield clean_chunk

                if full_text:
                    self.memory.add_assistant_message(full_text)
            else:
                # No tool calls: Direct assistant response
                full_text = sanitize_ai_response(message.content or "")
                self.memory.add_assistant_message(full_text)
                yield full_text

        except Exception as e:
            logger.error(f"GPT-4 Conversation Engine error: {e}")
            # Dynamic fallback to ensure unbroken live caller experience
            dual_result = await self.rag_service.query_dual_source(
                user_text,
                session_id=str(self.organization_id),
                conversation_history=self.memory.get_messages()
            )
            fallback = sanitize_ai_response(dual_result["answer"])
            self.memory.add_assistant_message(fallback)
            yield fallback
