import json
from typing import AsyncGenerator, Optional, Dict, Any
import openai
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logger import logger
from app.ai.memory_manager import MemoryManager
from app.ai.tools_definition import AI_TOOLS
from app.ai.tool_executor import ToolExecutor

class GPT4ConversationEngine:
    """Core AI Engine using GPT-4 with streaming audio response and function calling execution."""

    def __init__(self, memory_manager: MemoryManager, db: AsyncSession, organization_id: Any):
        self.memory = memory_manager
        self.client = openai.AsyncOpenAI(api_key=settings.OPENAI_API_KEY)
        self.model = settings.OPENAI_MODEL
        self.executor = ToolExecutor(db, organization_id)

    async def generate_response_stream(self, user_transcript: str) -> AsyncGenerator[str, None]:
        """Add user message, handle potential tool execution, and yield assistant response text chunks."""
        self.memory.add_user_message(user_transcript)

        # Fallback for dev / mock mode if API key is mock: Execute real 2-way database queries and mutations
        if not settings.OPENAI_API_KEY or settings.OPENAI_API_KEY == "sk-proj-mock-key-for-development":
            txt_lower = user_transcript.lower()

            if any(k in txt_lower for k in ["house", "property", "buy", "price", "bedroom", "looking for", "search", "list"]):
                tool_res_text = await self.executor.execute_tool("search_properties", json.dumps({"query": user_transcript}))
                try:
                    res_data = json.loads(tool_res_text)
                    results = res_data.get("results", [])
                    if results:
                        items_str = ", ".join([f"'{p['title']}' at {p['address']} (${p['price']:,.0f})" for p in results[:2]])
                        mock_resp = f"I queried our live database in real time. We have {items_str}. Would you like me to book a viewing appointment for you?"
                    else:
                        mock_resp = "I searched our live property database, but couldn't find an exact match right now. Would you like me to save your contact details so we can alert you when a listing arrives?"
                except Exception:
                    mock_resp = "I queried our live database. How else can I assist you with our available listings?"

            elif any(k in txt_lower for k in ["book", "appointment", "schedule", "viewing", "tour", "meet"]):
                tool_res_text = await self.executor.execute_tool("book_appointment", json.dumps({
                    "customer_name": "Caller",
                    "customer_phone": "+15550192834",
                    "start_time": "2026-10-05T14:00:00",
                    "title": "Property Viewing Appointment",
                    "notes": f"Requested during live call: {user_transcript}"
                }))
                mock_resp = "I have written this update directly into our live system! Your appointment has been booked in the database for tomorrow at 2:00 PM and saved to your lead record."

            elif any(k in txt_lower for k in ["lead", "contact", "my name is", "email", "phone", "number", "save"]):
                tool_res_text = await self.executor.execute_tool("save_lead", json.dumps({
                    "name": "Live Caller",
                    "phone": "+15550192834",
                    "notes": user_transcript
                }))
                mock_resp = "I have updated our live CRM database with your contact information and notes from this call."

            else:
                mock_resp = f"Thank you for saying '{user_transcript}'. Every statement in this call is being logged to our real-time database. I can search properties, check availability, or schedule appointments for you right now."

            self.memory.add_assistant_message(mock_resp)
            yield mock_resp
            return


        try:
            # 1. First completion call with tools enabled
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=self.memory.get_messages(),
                tools=AI_TOOLS,
                tool_choice="auto",
                temperature=0.7,
                stream=False
            )

            message = response.choices[0].message

            # 2. Handle Tool Calls if generated by GPT-4
            if message.tool_calls:
                # Add assistant tool call request to memory
                self.memory.add_raw_message(message.model_dump())

                for tool_call in message.tool_calls:
                    fn_name = tool_call.function.name
                    fn_args = tool_call.function.arguments
                    tool_result = await self.executor.execute_tool(fn_name, fn_args)
                    self.memory.add_tool_message(tool_call.id, tool_result)

                # Stream final response after tool execution
                stream = await self.client.chat.completions.create(
                    model=self.model,
                    messages=self.memory.get_messages(),
                    temperature=0.7,
                    stream=True
                )
                
                full_text = ""
                async for chunk in stream:
                    content = chunk.choices[0].delta.content or ""
                    if content:
                        full_text += content
                        yield content

                if full_text:
                    self.memory.add_assistant_message(full_text)
            else:
                # No tool calls: Stream direct assistant response
                full_text = message.content or ""
                self.memory.add_assistant_message(full_text)
                yield full_text

        except Exception as e:
            logger.error(f"GPT-4 Conversation Engine error: {e}")
            fallback = "I apologize, I experienced a brief processing interruption. Could you please repeat that?"
            yield fallback
